// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtCY1cYvBa5ZjgcPR3lnI0erIMsVR9enQ',
    appId: '1:51912556571:web:27980b5f077ecda5db38be',
    messagingSenderId: '51912556571',
    projectId: 'scout-c62fd',
    authDomain: 'scout-c62fd.firebaseapp.com',
    storageBucket: 'scout-c62fd.firebasestorage.app',
    measurementId: 'G-SVF5KSWVTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzfrfBxLlzt14pN3LzNFxCorDV1N6QqZU',
    appId: '1:51912556571:android:eb8b81710b496fc8db38be',
    messagingSenderId: '51912556571',
    projectId: 'scout-c62fd',
    storageBucket: 'scout-c62fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpPL3eC98VQnOTAKRhW-0GvBaNLxacIiU',
    appId: '1:51912556571:ios:78191c3c666101b7db38be',
    messagingSenderId: '51912556571',
    projectId: 'scout-c62fd',
    storageBucket: 'scout-c62fd.firebasestorage.app',
    iosBundleId: 'com.eventapp.scout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpPL3eC98VQnOTAKRhW-0GvBaNLxacIiU',
    appId: '1:51912556571:ios:62ca5ec65fb7568fdb38be',
    messagingSenderId: '51912556571',
    projectId: 'scout-c62fd',
    storageBucket: 'scout-c62fd.firebasestorage.app',
    iosBundleId: 'com.example.scoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtCY1cYvBa5ZjgcPR3lnI0erIMsVR9enQ',
    appId: '1:51912556571:web:e461d54e4e073777db38be',
    messagingSenderId: '51912556571',
    projectId: 'scout-c62fd',
    authDomain: 'scout-c62fd.firebaseapp.com',
    storageBucket: 'scout-c62fd.firebasestorage.app',
    measurementId: 'G-T9TVTG2XQR',
  );
}
